title: Martin Dvorak
email: martin.dvorak@ista.ac.at
description: Postdoc at the University of West Bohemia in Plzeň
github_username: madvorak

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
