title: Martin Dvorak
email: martin.dvorak@ista.ac.at
description: Ph.D. student at Institute of Science and Technology Austria (ISTA)
github_username: madvorak

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
