title: Martin Dvorak
email: martin.dvorak@ista.ac.at
description: Ph.D. student at Institute of Science and Technology Austria (ISTA)
github_username: madvorak

# Build settings
theme: jekyll-theme-time-machine
plugins:
  - jekyll-feed
